#!/bin/bash

# This identity script returns the MAC address of {{'pi4-v3': 'end0', 'pi02W': 'wlan0'}[mender_device_type | default("unknown")] | default("eth0") }} as the device identity.

set -ue

MAC_FILE=/sys/class/net/{{'pi4-v3': 'end0', 'pi02w': 'wlan0'}[mender_device_type | default("unknown")] | default("eth0") }}/address

if [ ! -f "${MAC_FILE}" ]
then
    >&2 echo "Error: ${MAC_FILE} not found!"
    exit 1
fi

echo "mac=$(cat ${MAC_FILE})"
